[package]
name = "martin-tile-utils"
version = "0.6.3"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>", "MapLibre contributors"]
description = "Utilities to help with map tile processing, such as type and compression detection. Used by the MapLibre's Martin tile server."
keywords = ["maps", "tiles", "mvt", "tileserver"]
categories = ["science::geo", "parsing"]
exclude = [
    # Exclude the fixtures directory from the package - it's only used for tests.
    "/fixtures",
]
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true

[dependencies]
brotli.workspace = true
dashmap.workspace = true
flate2.workspace = true
geo = "0.30.0"
geo-types = "0.7.17"
geojson = "0.24.2"
geojson-vt-rs = "0.1.1"
geozero = { version = "0.14.0", features = ["with-mvt"] }
mvt = "0.10.3"
proj = "0.30.0"
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
approx.workspace = true
rstest.workspace = true

[lints]
workspace = true
